export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
export const SORT_BY_ALPHABETICAL = 'SORT_BY_ALPHABETICAL';
export const SORT_BY_WEIGHT = 'SORT_BY_WEIGHT';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const SEARCH_DOGS_SUCCESS = 'SEARCH_DOGS_SUCCESS';